repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: "Check code using flake8"
  - repo: https://github.com/ambv/black
    rev: 23.10.1
    hooks:
      - id: black
        name: "Format code using black"
        language_version: python3.11
#  - repo: local
#    hooks:
#      - id: commit-checker
#        name: "Verify the commit message"
#        language: system
#        entry: ./commit-checker.sh
#        stages: [ commit-msg ]
